chore(infra): Import terraform state bucket (#195)
Import the state bucket

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -7,29 +7,47 @@ on:
         required: false
         type: boolean
         default: false
+    secrets:
+      BOT_APP_ID:
+        required: true
+      BOT_APP_PRIVATE_KEY:
+        required: true
 
 permissions:
-  contents: read
+  contents: write
   id-token: write
+  pull-requests: write
+  actions: read
 
 defaults:
   run:
     shell: bash
 
 env:
+  TERRAFORM_VERSION: 1.10.3
   GHA_WORKER_ROLE: arn:aws:iam::970547354432:role/gha-worker
 
 jobs:
 
   plan:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: infra
     steps:
+      -
+        name: Generate app token
+        id: app-token
+        uses: tibdex/github-app-token@v2
+        with:
+          app_id: ${{ secrets.BOT_APP_ID }}
+          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
       -
         uses: actions/checkout@v4
       -
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: "1.5.1"
+          terraform_version: ${{ env.TERRAFORM_VERSION }}
       -
         name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -38,13 +56,83 @@ jobs:
           role-session-name: ${{ github.run_id }}
           aws-region: us-west-2
       -
+        name: terraform fmt
+        run: terraform fmt
+      -
+        name: Detect changes
+        id: detect-changes
+        run: |
+          git add .
+          git status -s
+
+          if [ -n "$(git status -s)" ]; then
+            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
+          else
+            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
+          fi
+      -
+        name: Commit changes if detected
+        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
+        uses: planetscale/ghcommit-action@v0.2.0
+        env:
+          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
+        with:
+          commit_message: terraform fmt
+          repo: ${{ github.repository }}
+          branch: ${{ github.head_ref || github.ref_name }}
+      -
         name: terraform init
         run: terraform init
-        working-directory: infra
       -
         name: terraform plan
-        run: terraform plan
-        working-directory: infra
+        id: plan
+        run: |
+          # Wrapping to capture logs and exit status
+          (
+            set +e
+            terraform plan -no-color;
+            echo "$?" > "${{ runner.temp }}/plan-status.txt";
+          ) 2>&1 | tee "${{ runner.temp }}/plan-output.txt"
+
+          exit_code=$(cat "${{ runner.temp }}/plan-status.txt")
+          echo "exit_code=$exit_code" | tee -a "$GITHUB_OUTPUT"
+          
+          exit "$exit_code"
+      -
+        name: Capture plan logs
+        id: plan-logs
+        if: ${{ !cancelled() }}
+        run: |
+          stopToken=$(date '+%s')
+          echo "::stop-commands::${stopToken}"
+          {
+            echo 'logs<<EOF';
+            cat "${{ runner.temp }}/plan-output.txt";
+            echo 'EOF';
+          } | tee -a "$GITHUB_OUTPUT"
+          echo "::${stopToken}::"
+          
+          PLAN_SUMMARY=$(cat "${{ runner.temp }}/plan-output.txt" | sed -nE 's/Plan: (.+)\./\1/p')
+          echo "plan_summary=$PLAN_SUMMARY" | tee -a "$GITHUB_OUTPUT"
+      -
+        name: Comment plan result
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: ${{ !cancelled() }}
+        with:
+          recreate: true
+          header: terraform-plan
+          message: |
+            `terraform plan` ${{ steps.plan.outputs.exit_code == '0' && 'succeeded' || 'failed' }}
+
+            ${{ steps.plan-logs.outputs.plan_summary }}
+
+            <details>
+              <summary>plan result</summary>
+
+              ```
+              ${{ steps.plan-logs.outputs.logs }}
+              ```
+            </details>
 
   apply:
     needs: plan
@@ -57,7 +145,7 @@ jobs:
       -
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: "1.5.1"
+          terraform_version: ${{ env.TERRAFORM_VERSION }}
       -
         name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
